// Faction (阵营) index for the Red Alert unit banks.
//
// `redalert-sentences.ts` is generated by the scraper scripts, so faction data
// lives here as a hand-authored companion source (same pattern as the other
// curated banks): the scrapers keep writing sentences, this file keeps saying
// which faction each unit belongs to. Unit names must match the `unit` field in
// redalert-sentences.ts exactly.
//
// RA2 (含尤复的复仇 Yuri's Revenge) → Allied / Soviet / Yuri
// RA3 (含起义时刻 Uprising)        → Empire / Allied / Soviet

import { raSentencesByUnit, type RAGame, type RAUnitSentences } from './redalert-sentences';

export type RAFaction = 'Allied' | 'Soviet' | 'Yuri' | 'Empire' | 'Other';

export interface RAFactionMeta {
  /** English name as it appears in the source material. */
  en: string;
  /** Chinese name shown in the UI. */
  zh: string;
  /** Accent colour for the faction dot / chip. */
  color: string;
}

export const RA_FACTION_META: Record<RAFaction, RAFactionMeta> = {
  Allied: { en: 'Allied', zh: '盟军', color: '#3B6FD4' },
  Soviet: { en: 'Soviet', zh: '苏联', color: '#C4473A' },
  Yuri: { en: 'Yuri', zh: '尤里', color: '#7A4FC4' },
  Empire: { en: 'Empire', zh: '旭日帝国', color: '#C9821E' },
  Other: { en: 'Other', zh: '其他', color: '#8A8D9E' },
};

/** Display order of the factions inside each game. */
export const RA_GAME_FACTIONS: Record<RAGame, RAFaction[]> = {
  RA2: ['Allied', 'Soviet', 'Yuri'],
  RA3: ['Empire', 'Allied', 'Soviet'],
};

/** RA2 + 尤复的复仇 — 单位 → 阵营。 */
const RA2_UNIT_FACTIONS: Record<string, RAFaction> = {
  // ── 盟军 / Allied ──
  GI: 'Allied',
  Engineer: 'Allied',
  Spy: 'Allied',
  Sniper: 'Allied',
  'Navy SEAL': 'Allied',
  Tanya: 'Allied',
  'Chrono Legionnaire': 'Allied',
  'Grizzly Tank': 'Allied',
  IFV: 'Allied',
  'Prism tank': 'Allied',
  'Mirage tank': 'Allied',
  'Tank Buster': 'Allied',
  'Battle Fortress': 'Allied',
  'Mobile construction vehicle': 'Allied',
  'Chrono Miner': 'Allied',
  Rocketeer: 'Allied',
  Intruder: 'Allied',
  'Black Eagle': 'Allied',
  Nighthawk: 'Allied',
  Destroyer: 'Allied',
  'Aegis Cruiser': 'Allied',
  'Aircraft carrier': 'Allied',
  'Amphibious transport': 'Allied',
  Cowboy: 'Allied',
  Bodyguard: 'Allied',
  'Allied Civilian': 'Allied',
  'Allied Civilian Woman': 'Allied',
  'Professor Einstein': 'Allied',
  'Guardian GI': 'Allied',

  // ── 苏联 / Soviet ──
  Conscript: 'Soviet',
  'Flak trooper': 'Soviet',
  'Tesla trooper': 'Soviet',
  'Crazy Ivan': 'Soviet',
  Desolator: 'Soviet',
  Boris: 'Soviet',
  'Soviet Engineer': 'Soviet',
  'Rhino tank': 'Soviet',
  'Flak Track': 'Soviet',
  'Apocalypse tank': 'Soviet',
  'Tesla tank': 'Soviet',
  'Demolition truck': 'Soviet',
  'Soviet MCV': 'Soviet',
  'War Miner': 'Soviet',
  'V3 Rocket Launcher': 'Soviet',
  'Kirov airship': 'Soviet',
  'Siege Chopper': 'Soviet',
  'Typhoon Attack Sub': 'Soviet',
  'Sea Scorpion': 'Soviet',
  Dreadnought: 'Soviet',
  'Boomer Submarine': 'Soviet',
  'Soviet Hovercraft': 'Soviet',
  'MiG Fighter': 'Soviet',
  Cosmonaut: 'Soviet',
  'Soviet Civilian': 'Soviet',
  'Soviet Civilian Woman': 'Soviet',
  'Premier Romanov': 'Soviet',
  'Freed Slave': 'Soviet',
  Terrorist: 'Soviet',

  // ── 尤里 / Yuri ──
  Yuri: 'Yuri',
  Initiate: 'Yuri',
  'Yuri Clone': 'Yuri',
  'Yuri Prime': 'Yuri',
  Brute: 'Yuri',
  Virus: 'Yuri',
  'Gattling Tank': 'Yuri',
  'Lasher Tank': 'Yuri',
  Magnetron: 'Yuri',
  Mastermind: 'Yuri',
  'Floating Disc': 'Yuri',
  'Slave Miner': 'Yuri',
  'Yuri MCV': 'Yuri',
  'Yuri Hovercraft': 'Yuri',
};

/** RA3 + 起义时刻 — 单位 → 阵营。 */
const RA3_UNIT_FACTIONS: Record<string, RAFaction> = {
  // ── 旭日帝国 / Empire ──
  'Empire Warrior': 'Empire',
  'Tank Killer': 'Empire',
  'Imperial Engineer': 'Empire',
  Shinobi: 'Empire',
  'Rocket Angel': 'Empire',
  'Yuriko Omega': 'Empire',
  'Empire Ore Collector': 'Empire',
  'Sudden Transport': 'Empire',
  'Mecha Tengu': 'Empire',
  'Tsunami Tank': 'Empire',
  'Striker-VX': 'Empire',
  'King Oni': 'Empire',
  'Wave-Force Artillery': 'Empire',
  'Empire Construction Vehicle': 'Empire',
  'Yari Mini-Sub': 'Empire',
  'Sea Wing': 'Empire',
  'Naginata Cruiser': 'Empire',
  'Shogun Battleship': 'Empire',
  'Archer Maiden': 'Empire',
  'Steel Ronin': 'Empire',
  'Giga Fortress': 'Empire',

  // ── 盟军 / Allied ──
  Peacekeeper: 'Allied',
  'Javelin Soldier': 'Allied',
  'Allied engineer': 'Allied',
  Spy: 'Allied',
  Tanya: 'Allied',
  Prospector: 'Allied',
  'Riptide ACV': 'Allied',
  'Multigunner IFV': 'Allied',
  'Guardian Tank': 'Allied',
  'Athena Cannon': 'Allied',
  'Mirage tank': 'Allied',
  'Allied Construction Vehicle': 'Allied',
  Vindicator: 'Allied',
  'Apollo Fighter': 'Allied',
  Cryocopter: 'Allied',
  'Century Bomber': 'Allied',
  Hydrofoil: 'Allied',
  'Assault Destroyer': 'Allied',
  'Aircraft carrier': 'Allied',
  'Cryo Legionnaire': 'Allied',
  Pacifier: 'Allied',
  'Future Tank X-1': 'Allied',
  Harbinger: 'Allied',

  // ── 苏联 / Soviet ──
  Conscript: 'Soviet',
  'Flak trooper': 'Soviet',
  'Soviet Engineer': 'Soviet',
  'Tesla trooper': 'Soviet',
  Natasha: 'Soviet',
  'Soviet ore collector': 'Soviet',
  Sputnik: 'Soviet',
  Sickle: 'Soviet',
  Bullfrog: 'Soviet',
  'Hammer Tank': 'Soviet',
  'Apocalypse tank': 'Soviet',
  'V4 Rocket Launcher': 'Soviet',
  'Soviet Construction Vehicle': 'Soviet',
  Twinblade: 'Soviet',
  'MiG Fighter': 'Soviet',
  'Kirov airship': 'Soviet',
  Stingray: 'Soviet',
  Akula: 'Soviet',
  Dreadnought: 'Soviet',
  'Mortar Cycle': 'Soviet',
  Desolator: 'Soviet',
  Reaper: 'Soviet',
  Grinder: 'Soviet',
};

/** Faction of a single unit. Returns `undefined` when the unit is not indexed. */
export function unitFaction(game: RAGame, unit: string): RAFaction | undefined {
  return (game === 'RA2' ? RA2_UNIT_FACTIONS : RA3_UNIT_FACTIONS)[unit];
}

export interface RAFactionGroup {
  faction: RAFaction;
  /** English faction name. */
  en: string;
  /** Chinese faction name (UI label). */
  zh: string;
  /** Accent colour. */
  color: string;
  /** Units of this faction, in the canonical browse order. */
  units: RAUnitSentences[];
  /** Total sentences across the group. */
  sentenceCount: number;
}

/**
 * Units of one game grouped by faction, in `RA_GAME_FACTIONS` order.
 * Units missing from the faction tables are never dropped — they end up in the
 * trailing `Other` group so the browse page always shows the whole roster.
 */
export function raUnitsByFaction(game: RAGame): RAFactionGroup[] {
  const buckets = new Map<RAFaction, RAUnitSentences[]>();
  const unindexed: RAUnitSentences[] = [];
  for (const f of RA_GAME_FACTIONS[game]) buckets.set(f, []);
  for (const u of raSentencesByUnit()) {
    if (u.game !== game) continue;
    const f = unitFaction(game, u.unit);
    if (f) buckets.get(f)!.push(u);
    else unindexed.push(u);
  }

  const groups: RAFactionGroup[] = [];
  for (const f of RA_GAME_FACTIONS[game]) {
    const units = buckets.get(f)!;
    if (units.length) groups.push(toGroup(f, units));
  }
  if (unindexed.length) groups.push(toGroup('Other', unindexed));
  return groups;
}

function toGroup(faction: RAFaction, units: RAUnitSentences[]): RAFactionGroup {
  const meta = RA_FACTION_META[faction];
  return {
    faction,
    en: meta.en,
    zh: meta.zh,
    color: meta.color,
    units,
    sentenceCount: units.reduce((n, u) => n + u.sentences.length, 0),
  };
}
