// AUTO-GENERATED by scripts/scrape-redalert.mjs — do not edit by hand.
// Red Alert 2 & 3 unit voice quotes (source: cnc.fandom.com, CC-BY-SA). Internal use.

export interface RAQuoteGroup {
  /** Chinese action label (选中/移动/攻击/…). */
  label: string;
  lines: string[];
}

export interface RAUnit {
  name: string;
  /** "RA2" | "RA3" */
  game: string;
  groups: RAQuoteGroup[];
}

export const REDALERT_UNITS: RAUnit[] = [
  {
    "name": "Aircraft carrier",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Aircraft carrier responding.",
          "Flight deck cleared.",
          "Preparin' jets for takeoff.",
          "Pride of the Allied Navy!",
          "The largest ship in the fleet."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Charting path.",
          "Slow and steady.",
          "Hold the course.",
          "New heading set.",
          "Coordinates confirmed."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Hornets in the air!",
          "Commencing attack run!",
          "Release the swarm!",
          "Naval airfleet engaging!",
          "We have a target!"
        ]
      }
    ]
  },
  {
    "name": "Amphibious transport",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Welcome aboard!",
          "Having a nice day?",
          "How about an adventure?",
          "Plenty of window seats!",
          "See the countryside!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "We're on our way!",
          "Let's take the scenic route.",
          "Wanna stop for a picture?",
          "What a view!",
          "Enjoy the ride!"
        ]
      }
    ]
  },
  {
    "name": "Apocalypse tank",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "The instrument of doom.",
          "It is day of judgement.",
          "Armageddon is here.",
          "Soviet power supreme.",
          "Annihilating."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "They will run in fear.",
          "I cast a deadly shadow.",
          "It will soon be a wasteland.",
          "Excellent.",
          "Be patient."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Eradicate them.",
          "The end is at hand.",
          "These will be your last moments.",
          "Taste your mortality.",
          "The apocalypse has begun.",
          "Bringing down the hammer."
        ]
      }
    ]
  },
  {
    "name": "Conscript",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Awaiting orders.",
          "Comrade?",
          "Conscript reporting."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Da!",
          "For the Union!",
          "Moving out.",
          "Order received."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Attacking.",
          "For home country!",
          "For Mother Russia!",
          "You are sure?"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "(crying)",
          "Mommy!",
          "We are being attacked!"
        ]
      }
    ]
  },
  {
    "name": "Demolition truck",
    "game": "RA2",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "My truck is loaded!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "My truck is loaded!",
          "Let's make a delivery!",
          "I shall avenge us!",
          "Why don't you drive?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "One way trip!",
          "As you wish!",
          "Watch out for the bumps!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "For my people!",
          "I am prepared to die!",
          "It will be a smoking crater!",
          "Don't wait up for me!",
          "Aaaaah-kakakakaka!"
        ]
      }
    ]
  },
  {
    "name": "Desolator",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Desolator ready.",
          "(heavy breathing)",
          "Ready for meltdown.",
          "Reactor ready!",
          "Mercury rising."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Find a hot spot!",
          "Scorched earth!",
          "Spread the doom!",
          "There goes the neighborhood!",
          "It will be a silent spring."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Tagged for extinction!",
          "Make it glow!",
          "Let's heat them up!",
          "Here comes the sun!",
          "The end is near!",
          "Let's make an oasis of death!"
        ]
      }
    ]
  },
  {
    "name": "Destroyer",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Allied ship reporting.",
          "Navigation systems ready.",
          "Captain on the bridge!",
          "Standing by."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Speed to full.",
          "Main engines engaged.",
          "Rudder set for new heading.",
          "Aye, commander.",
          "Steady as she goes."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Enemy spotted.",
          "Attacking",
          "Battle stations!"
        ]
      }
    ]
  },
  {
    "name": "Dreadnought",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Ship reporting.",
          "Vessel ready.",
          "Yes, commander?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Captain confirming.",
          "Course set.",
          "Navigating!",
          "Engines engaged."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Target sighted!",
          "Fire at will!",
          "Cruise and fire!"
        ]
      }
    ]
  },
  {
    "name": "Flak trooper",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "At least I have job.",
          "Flak trooper reporting.",
          "Orders, comrade?",
          "Ready."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Да! (Yes!)",
          "I'm going!",
          "Moving out!",
          "This gun is heavy."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "A little flak?",
          "Clouds of death!",
          "Flak attack!",
          "This will be messy."
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Help me, Romanov!",
          "I can't see through flak!",
          "I'm just one man!",
          "They're shooting me!"
        ]
      }
    ]
  },
  {
    "name": "Kirov airship",
    "game": "RA2",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Kirov reporting."
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Kirov reporting.",
          "Acknowledged.",
          "Airship ready.",
          "Helium mix optimal."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Setting new course.",
          "Maneuver props engaged.",
          "Bearing set."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Bombing bays ready.",
          "Target acquired.",
          "Closing on target.",
          "Bombardiers, to your stations!"
        ]
      },
      {
        "label": "阵亡",
        "lines": [
          "Mayday! Mayday!",
          "We're losing altitude!",
          "She's going to blow!"
        ]
      }
    ]
  },
  {
    "name": "Mirage tank",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Mean, green, and unseen.",
          "Aren't the trees lovely?",
          "Perfect hideout.",
          "Natural sanctuary.",
          "Want some shade?",
          "Nobody's here but us trees!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Layin' low.",
          "Look natural.",
          "Creeping ahead.",
          "On the prowl.",
          "Re-planting.",
          "Going mobile.",
          "Now you see me, soon you won't."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Surprise!",
          "Ha-ha!",
          "Sneak attack!",
          "One more for the landfill!",
          "Time for an ambush!"
        ]
      }
    ]
  },
  {
    "name": "Mobile construction vehicle",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Packed up and ready.",
          "Materials checked and cleared.",
          "Blueprints ready, sir.",
          "Allied schematics on hand.",
          "Let's set up shop!",
          "What's the word?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Wanna set up over there?",
          "Let's find some flat land!",
          "Location is key.",
          "A new location, commander?",
          "Show's on the road.",
          "Loaded up and truckin'!"
        ]
      }
    ]
  },
  {
    "name": "Navy SEAL",
    "game": "RA2",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "SEAL ready!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "SEAL ready!",
          "I'm your man!",
          "A li'l C-4 knockin' at your door. (unused, given to the chrono commando)",
          "Who's your daddy?",
          "Let's get it on!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Hoo-rah!",
          "Cover me.",
          "How 'bout a swim?"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Enemy in my sights!",
          "I got him!",
          "This is too easy!",
          "Goin' down!",
          "Special delivery!"
        ]
      }
    ]
  },
  {
    "name": "Prism tank",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Prism tank in order, sir.",
          "Dioptic manifolds clear.",
          "Lens shifters in working condition.",
          "Prism sensors stable.",
          "Panels charged."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Compensating for terrain flux.",
          "Estimating distortion error.",
          "Positional data received.",
          "New coordinates processed.",
          "Readjusting stabilizers."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Magnifiers activated.",
          "Calculating reflection arcs.",
          "Resolving target coordinates.",
          "Intensifying light trajectory.",
          "Focusing light energy."
        ]
      }
    ]
  },
  {
    "name": "Rhino tank",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Vehicle reporting.",
          "Ready, comrade.",
          "Awaiting orders."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Location confirmed.",
          "Moving.",
          "Changing position."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Target sighted.",
          "Encountering enemy!",
          "We will bury them!",
          "Attacking!"
        ]
      }
    ]
  },
  {
    "name": "Sniper",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Sniper ready.",
          "Give me a target.",
          "Give me a job.",
          "Eliminate 'em."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Proceeding to vantage point.",
          "Just give me a clear view.",
          "I love to camp.",
          "Just get me close enough.",
          "Settling in."
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Taking him out.",
          "He's in my scope.",
          "He's a dead man."
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Run for cover!",
          "I need support!",
          "I'm in too close!"
        ]
      }
    ]
  },
  {
    "name": "Tanya",
    "game": "RA2",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "(maniacal laughter)"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Anytime, boss.",
          "You got an order?",
          "Where's the party?",
          "Show me the way!",
          "How about some action?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "I'm there.",
          "How 'bout a target?",
          "On my way.",
          "Movin' out, boss.",
          "I'm on it.",
          "Shake it, baby!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Cha-ching!",
          "(maniacal laughter)",
          "Locked and loaded!",
          "Yeah, baby!"
        ]
      }
    ]
  },
  {
    "name": "Terrorist",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "What are your conditions?",
          "We must revolt!",
          "Need a smuggler?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Vamos, muchachos!",
          "On my way!",
          "I go freely!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Adios, amigos!",
          "Here's a hot papaya!",
          "For the Republic!",
          "Traitors must be eliminated!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Take me back to Havana!",
          "Ayyyy!",
          "I've been discovered!"
        ]
      }
    ]
  },
  {
    "name": "Tesla tank",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Generators humming.",
          "Wired for destruction!",
          "Capacitor at full charge!",
          "I have the power!",
          "Reading meters."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Positively.",
          "Efficient and clean.",
          "Maximum power!",
          "This sparks my curiosity.",
          "Nothing wasted!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Free hook-ups!",
          "No charge for extra power!",
          "Prepare for rolling blackout!",
          "Need a little boost?"
        ]
      }
    ]
  },
  {
    "name": "Tesla trooper",
    "game": "RA2",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Tesla suit ready.",
          "Charging up!",
          "Electrodes ready!",
          "Checking connection.",
          "Extra crispy! (cut)"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Going to source.",
          "Moving out.",
          "Yes, comrade.",
          "Surging forward.",
          "Electrician in the field.",
          "Rubber shoes in motion!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "2000 Volts coming up!",
          "He's fried.",
          "Completing circuit.",
          "Let the joules flow!",
          "Commencing shock therapy.",
          "Congratulations, you've been discharged! (cut)"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Ground yourselves!",
          "Reinforcements!",
          "I am hit!"
        ]
      }
    ]
  },
  {
    "name": "Aircraft carrier",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Aircraft carrier leaving port!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Pride of the Allied fleet!",
          "Allied air fleet!",
          "Captain here!",
          "Carrier at sea!",
          "All inspections complete!",
          "Flight deck cleared!",
          "Prepared for war!",
          "Tall and proud!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Engines at full!",
          "Charting course!",
          "Heading set!",
          "Understood!",
          "Everyone, take note!",
          "Very well!",
          "Set a course!",
          "Slow and steady!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Engage!",
          "Advance to bombing range!",
          "Prepare the jets!",
          "Standby for bombing run!",
          "The order has been made!",
          "We will end this quickly!",
          "Send another wave!",
          "To the Skies!",
          "There's the target, go!",
          "Destroy it!",
          "Do not let it stand!",
          "Now, descend upon them!",
          "Commence attack run!"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Fire the EMP!",
          "EMP missiles!",
          "Launch the Blackout Missile!",
          "Shut them down!",
          "Put a stop to them!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Ready the next offensive!",
          "Keep the decks clear!",
          "Bombardment underway!",
          "Air fleet engaged!",
          "Fly with glory!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Have they breached the hull?",
          "Where are we hit?",
          "All hands! All hands!",
          "They're trying to sink her!",
          "They will pay for this!"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "Send her back home!",
          "She'll need repairs!",
          "Flee these rough waters!",
          "We can still save her!"
        ]
      }
    ]
  },
  {
    "name": "Allied engineer",
    "game": "RA3",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "On time as always!",
          "Tools ready!",
          "How can I help?",
          "Oh, hi!",
          "I'm here if you need me!",
          "Hey there, command!",
          "Hello? Hello?",
          "Need a repair?",
          "I'm listening, sir!",
          "Engineering!",
          "I've got the knowledge!",
          "I have the tools!",
          "Engineer on duty!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Okay!",
          "I won't be late!",
          "Whatever you say, sir!",
          "Excelsior!",
          "Yes, sir!",
          "Alrightey then!",
          "Comin' out!",
          "Ooh, get me a towel!",
          "Aww, I was just getting used to it!",
          "Last one out is a rotten egg!",
          "Is it safe in there?",
          "...what about sharks?",
          "Cannonball!",
          "Maybe you should go in first!"
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "I thought you'd never ask!",
          "Don't have to tell me twice!",
          "Ooh! Do they have Internet?"
        ]
      },
      {
        "label": "潜入/占领",
        "lines": [
          "Analyzing schematics!",
          "Studying blueprints!",
          "Got the plans right here!",
          "I know this part!"
        ]
      },
      {
        "label": "维修",
        "lines": [
          "Repairing!",
          "I know just the trick!",
          "I can fix it!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "I'm unarmed!",
          "Get 'em off me! Get 'em off me!",
          "Get me outta here!",
          "Help!"
        ]
      }
    ]
  },
  {
    "name": "Apocalypse tank",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "The Apocalypse has begun.",
          "Armageddon is here."
        ]
      },
      {
        "label": "选中",
        "lines": [
          "We wait.",
          "Soviet Power Supreme!",
          "I have the final say...",
          "The Instrument of DOOM.",
          "It is day of judgement.",
          "Where are they?",
          "Vengeance is near..."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "We cannot be stopped.",
          "It is time!",
          "They will run in fear.",
          "Make a path...",
          "They will pay.",
          "Excellent!",
          "Be patient...",
          "We know they are here..."
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Crush them!",
          "Now!",
          "Amusing!",
          "Pathetic!",
          "Kill it!",
          "Leave nothing!",
          "Eradicate them!",
          "With pleasure!",
          "A fine choice...",
          "An appetizer...",
          "This one looks good!",
          "GET OVER HERE!",
          "YOU CANNOT ESCAPE!",
          "Your turn!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "WE WILL BURY THEM!",
          "Annihilating!",
          "The day has come!",
          "At last!",
          "So it begins!",
          "*Maniacal Sadistic Laughter*"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Such Fools!",
          "The end is at hand!",
          "It's soon shall be over!",
          "This will be their last moments!",
          "Their end draws near!",
          "We shall end this!",
          "It will soon be a wasteland!",
          "There is no mercy!"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "Armageddon will wait!",
          "Soviet Power must be preserved!!",
          "Let them be!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "The fools cannot hinder me!",
          "The Apocalypse cannot be stopped!",
          "I will not be interrupted!",
          "They have not accepted their fate!"
        ]
      }
    ]
  },
  {
    "name": "Conscript",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Conscript training finished!",
          "Ready to fight for Union!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Conscript excited to fight!",
          "Conscript here!",
          "I suppose to do something?",
          "Here I am!",
          "Huh? Me?",
          "I wasn't doing anything!",
          "Is it time?",
          "Show me what to do!",
          "This is nice clothes!",
          "We serve glorious Union!",
          "I make Premier proud!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "I can do!",
          "As fast as I can!",
          "Yes sir!",
          "Oh, okay!",
          "Moving!",
          "I go!",
          "Whatever you say!",
          "Have we won yet?",
          "Of course!"
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "Good, let's take a break!",
          "They have television in there?",
          "Ahh... Thank you!",
          "What's in here?",
          "It looks dark...",
          "Get out of there!",
          "Make room for Mother Russia!",
          "Kick them out!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "For the Union!",
          "Attack!",
          "For Mother Russia!",
          "Firing weapon!",
          "Kill them like watermelon!",
          "Now?",
          "Who's with me?",
          "Field promotion, here I come!",
          "I'll do it!",
          "Finally, the real thing!",
          "We march to victory!",
          "It's them!",
          "Premier will be very proud!",
          "At last, real battle!"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "They will burn!",
          "Ura!",
          "Throw the fire!",
          "Vot tak! (\"Like this!\" in Russian)",
          "Catch this!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "We're shooting the enemy!",
          "The enemy's here!",
          "Together comrades!",
          "Just like training video!",
          "I fight bravely!",
          "Dirty dogs!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "I don't like this anymore!",
          "They have guns too...?",
          "They're shooting at me!",
          "Tell the Premier, I've been wounded!",
          "Next time I drive tank okay?",
          "Atas, patsany! (\"Watch out, dudes!\" in Russian)"
        ]
      }
    ]
  },
  {
    "name": "Dreadnought",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "We launch this day in the name of the U.S.S.R.! (unused)",
          "Are you prepared to fight, Comrades?!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Dreadnought and her crew are ready!",
          "The seas will run red!",
          "We rule these waters!",
          "Enemies of the Union shall burn!",
          "This is our day, comrades!",
          "Seafaring patriots!",
          "If Lenin could see us now..."
        ]
      },
      {
        "label": "移动",
        "lines": [
          "These waters belongs to Russia!",
          "The seas tremble beneath us!",
          "Onward!",
          "Forward, Comrades!",
          "A majestic sight we must be...",
          "Let us embrace the seas!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Destroy them!",
          "They must fall!",
          "Our time has come!",
          "Smite them down!",
          "They shall be no more!",
          "Attack!",
          "End their arrogance!",
          "To war!",
          "These enemies will perish!",
          "None shall oppose the Union!",
          "We must destroy them!",
          "Prepare all launchers!",
          "The moment we have waited for!",
          "We will fight for our noble cause!",
          "Take your positions, comrades!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "We shall prevail!",
          "Do not relent!",
          "Victory is at hand!",
          "They are fools to oppose us!",
          "Stand together and fight, comrades!",
          "Can you feel the Soviet might?!",
          "Patriotism begets victory!",
          "Woe unto our hapless foes!",
          "Continue all launchers!",
          "Their surrender is inevitable!",
          "We fight to the last man and rocket!"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "The Union demands our return!",
          "Our noble voyage must end.",
          "We shall arrive as heroes.",
          "It was a glorious battle..."
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "We have withstood worse threats...",
          "Our hull cannot be breached so easily...",
          "They cannot damage our will!",
          "Steel yourselves, Comrades!",
          "Do not let fear take hold!"
        ]
      }
    ]
  },
  {
    "name": "Flak trooper",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Flak trooper, doing my time!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Flak trooper!",
          "Yep!",
          "Where's that food you promised?",
          "What's it gonna be?",
          "Someone's gonna pay!",
          "Just wait 'til I get these chains off!",
          "Who wants a piece of this?",
          "I'm innocent, I swear!",
          "Beats being in the gulag...",
          "So this what they call community service...",
          "You're gonna make me carry this?!",
          "I have to carry this around?"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Mines ready!",
          "Mines!",
          "Flak ready!",
          "Alright, flak cannon!",
          "Hold this for me!",
          "Stash it!",
          "Kaboom!",
          "Hehehe!",
          "Let 'em have it!",
          "Hehehe....!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Okay, but then I rest!",
          "I'm going!",
          "Whatever!",
          "Alright!",
          "If you say so!",
          "Ye! Ye!",
          "What do I get?",
          "Yes warden!"
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "Get in there!",
          "Whats in there?",
          "They serve food?",
          "Just don't lock the door!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Flak 'em!",
          "Kill!",
          "Punish them!",
          "Is he next?",
          "Here's your share!",
          "There, see what it's like!",
          "They're staring us down!",
          "You ain't hiding from nobody!",
          "Think you're safe up there?!",
          "Heads up!",
          "A little butterfly!",
          "Na khvatay! (Here grab it!)",
          "Let's see how this thing works...",
          "What have I got to lose!?",
          "They have it coming!",
          "Let's get this over with!",
          "Time for their medicine!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "That's right, sucker!",
          "And there's more coming!",
          "Ah, don't cry now!",
          "Come on, punk!",
          "Let's riot!",
          "Can I go free now?",
          "So this is war!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "I've seen worse!",
          "They don't scare me!",
          "They won't take me alive!",
          "You think that hurts?",
          "Ahh! That hurts!",
          "Nu ty kozyol! ( Russian: \"Hey, you a**hole\" )"
        ]
      }
    ]
  },
  {
    "name": "Kirov airship",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Kirov reporting!",
          "Kirov rising!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Let's pay a visit!",
          "I have something for them!",
          "I'm a giver!",
          "Have I missed anyone?",
          "Who's left?",
          "Where the next stop?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Very well!",
          "Mm Hmm!",
          "Any friends along the way?",
          "We wait there!",
          "Soon!",
          "In time!",
          "A new course!",
          "See you there!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Another one?",
          "Leave... nothing!",
          "Destroy the place!",
          "It's still standing?",
          "Another for good measure!",
          "Huhh! Can't be too generous!",
          "I don't think we've met...",
          "That one looks good...",
          "Never thought you ask!",
          "How pretty!",
          "Well, look at that!",
          "Let's go say hello!",
          "Don't mind if I do!",
          "Leave our mark!",
          "Excellent!",
          "Look what we have here!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Ahh! The sounds of destruction!",
          "Drop another load!",
          "Ohh yeah!",
          "Uhh! Thats nice!",
          "*sniffs* Do you smell that?...",
          "Hehehe, that's right!",
          "Aw... look, is that your house?"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "All the way back!?",
          "I'll ignore their insults!",
          "Fine, we going home!",
          "Take her back!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "The pests are rack'ting up!",
          "They annoying me!",
          "Where are my escorts?!",
          "Stop this nuisance!",
          "Why are they so unfriendly?!",
          "Get away from me!"
        ]
      }
    ]
  },
  {
    "name": "Mirage tank",
    "game": "RA3",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "You call for the mirage?",
          "Mirage Tank!",
          "We await your direction!",
          "Camouflage, standing by!",
          "Bonjour, Commander!",
          "What should it be?",
          "Mirage tank, operational!",
          "Mirage field, standing by!"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Do they suspect we're here?",
          "Is it time?",
          "Wait for the right moment!",
          "Keep still!",
          "Shhh!",
          "Blending in!",
          "Nothing here but trees!",
          "Maintain cloaking field!",
          "Careful now!",
          "We're out in the open!",
          "Take it steady!",
          "They may see us now!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Place to place!",
          "On the prowl!",
          "To the next mirage!",
          "Proceed!",
          "Into the background!",
          "Understood!",
          "Prepare to blend!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Ambush them!",
          "Commence attack!",
          "Now, now!",
          "Fire at will!",
          "Now is the time!",
          "AHA!",
          "C'était fatal!",
          "Attack!",
          "Don't let them see us coming!",
          "Approaching the target!",
          "Track them down!",
          "It's time to play our hand!",
          "Now's our chance!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Firing Spectrum Cannon!",
          "End it quickly!",
          "Au Revoir! (French for \"Goodbye!\")",
          "Again, AGAIN!",
          "Don't let them leave!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "How bad are we hit?",
          "They found us!",
          "We're taking damage!"
        ]
      }
    ]
  },
  {
    "name": "Soviet ore collector",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Ready for the collection!",
          "The Union must be funded!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Collector!",
          "It is in good hands!",
          "A noble task!",
          "We must all do our part!",
          "Without questions!",
          "It is for the good of all!",
          "Precautions are necessary!",
          "We are closed!",
          "We must protect it!",
          "Is danger still near?",
          "Are they gone yet?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "We still have collecting to do!",
          "Shouldn't we be working!",
          "Laziness will not be tolerated!",
          "And what about the collection?",
          "Is this necessary?",
          "A detour?",
          "If need be!",
          "Transporting!",
          "Updating manifest!"
        ]
      },
      {
        "label": "采矿",
        "lines": [
          "The Union will redistribute!",
          "Ready the paperwork!",
          "All will be accounted for!",
          "The wealth must be shared!",
          "To the Motherland!",
          "We must meet our quota!",
          "The Union requires it!",
          "War is expensive!",
          "It will be well spent!",
          "This is for the people!"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "Save the collection!",
          "Take it back to the people!",
          "We must return it to safety!",
          "Quickly!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "The collection is in danger!",
          "We are being attacked!",
          "Help! Bandits!",
          "They're trying to stop me!",
          "Do something before it is too late!"
        ]
      }
    ]
  },
  {
    "name": "Spy",
    "game": "RA3",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Ready to infiltrate!",
          "Spy ready!",
          "Agent here.",
          "What news, my friend?",
          "Good day, sir.",
          "Disguise ready!",
          "Commander?",
          "Mission, sir?",
          "Give me a plan!",
          "Have a disguise in mind?"
        ]
      },
      {
        "label": "潜入/占领",
        "lines": [
          "Under cover!",
          "Like my new look?",
          "Watch out for scouts!",
          "I don't like bears.",
          "Quickly now, before I'm spotted.",
          "How's the disguise holding up?",
          "I'll make myself at home!",
          "Hmm, don't mind if I do!",
          "I'll have a look around!",
          "Stand by for infiltration.",
          "You like that one aye?",
          "I'll see what I can do!",
          "Let's see what they've got!",
          "A good plan, I might add!.",
          "Come on, fight for the winning team!",
          "Every man has his price!",
          "We pay handsomely!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Of course sir.",
          "For King and Country!",
          "Yes sir.",
          "On my way.",
          "Operation under way.",
          "Yes, I copy.",
          "Indeed.",
          "Yes commander.",
          "Is it clear?",
          "Remember - I'm unarmed.",
          "Cheers.",
          "On it, like a bonnet!",
          "I trust the coast is clear?",
          "Ahh, a day at the beach.",
          "Have my towel ready?",
          "Ahh, refreshing!",
          "Wet suit ready.",
          "Will my hair get wet?",
          "Yes, I could go for a dip."
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "I'll meet you in the lobby,",
          "Luxury suite, if you don't mind?",
          "Top floor, please!?"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "Ahh, what happened to the plan?",
          "Where's my escape route?",
          "Hello? I'm ready for the rescue team!",
          "I've been spotted!",
          "They found me out!",
          "It's a trap!",
          "I'm unarmed!",
          "Could use some evac!"
        ]
      }
    ]
  },
  {
    "name": "Tanya",
    "game": "RA3",
    "groups": [
      {
        "label": "选中",
        "lines": [
          "Let's rock!",
          "Let's do it!",
          "Tanya here!",
          "Hey, what's up?",
          "Where do you need me?",
          "You got a target?",
          "Locked and loaded!",
          "Got something for me?",
          "Where's the party?",
          "Tanya here, ready to go!",
          "How about some action?"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "On my way!",
          "You got it!",
          "Copy that",
          "I'm on it!",
          "I'm there!",
          "Move it out!",
          "Sure thing!",
          "Making way!",
          "Let's take a walk!",
          "Back on my feet!",
          "That's enough of that!",
          "I'm good for a swim!",
          "Let's hit some wave!",
          "I'm part barracuda!"
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "I like it!",
          "I can hangout there!",
          "I'll take it!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Good night!",
          "Say goodbye!",
          "Go back to sleep!",
          "Cha ching!!",
          "Don't blink!",
          "Later, chump!",
          "Another loser!",
          "Knock! Knock!",
          "That one will blow up real good!",
          "C4 coming through!",
          "Hope they're wearing seatbelts!",
          "Let's give it a wax job!",
          "Time for a demo derby!",
          "Oh my!",
          "No problem!",
          "I'll take this one!",
          "Going after 'em!",
          "I bet he could use a rest!",
          "Is that it, just that one?",
          "Hey you, wait up!",
          "No sweat!"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "See ya!",
          "I'm outta here!",
          "Coming home!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Headshot!",
          "Ye!",
          "Dirt naps all around.",
          "Hahaha!",
          "This is my playground!",
          "Cha ching!!",
          "Step right up!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "I think I'm hit!",
          "Ouch, that one nicked me!",
          "Just a scratch!",
          "They are getting a little restless out here!",
          "That all you got?",
          "Commander, what are you waiting for?",
          "Permission to use time belt?",
          "Medic?!",
          "Don't you dare let me die out here!",
          "A little help?!"
        ]
      }
    ]
  },
  {
    "name": "Tesla tank",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Like my new treads?!",
          "Tesla tank, charge complete!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Who needs a jump?",
          "Capacitators ready!",
          "Electrodes primed!",
          "I'm wired!",
          "Fully shielded!",
          "Grease Lightning!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Generators humming!",
          "Hmm, good power!",
          "Beats walking!",
          "Like the handling!"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Sorry if I a turn off!",
          "I'm conserving!",
          "Blackout anyone?",
          "Let's play in the field!",
          "Lights out!",
          "No overcharge protection!",
          "Let's make contact!",
          "It's the recycled energy!",
          "I'll charge it up!",
          "Give it a boost!",
          "Let's turn is on!"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Let the juice flow!",
          "Light 'em up!",
          "Hitting switch!",
          "Clear!",
          "AC/DC!",
          "They could use a little boost!",
          "Illuminating!",
          "Completing circuit!",
          "Like a christmas tree!",
          "Is recycled energy!",
          "Charging up!",
          "Let's light them up!",
          "Time for a shocker!",
          "Insulation won't help!",
          "He's fried!",
          "Incoming storm!",
          "Here's your electric bill!",
          "Charge!",
          "Like a Christmas tree!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Just go with a flow!",
          "Not a bad conductor!",
          "Electricity is in the air!",
          "Extra crispy!",
          "No resistance!",
          "It all soon be over!"
        ]
      },
      {
        "label": "撤退",
        "lines": [
          "Going to source!",
          "Heading back for recharge!",
          "Don't recycle me!",
          "Got a bolt!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "What happened to my shielding?!!",
          "Hey, don't be so negative!",
          "They're giving me static!",
          "I may need shock therapy!",
          "Was it something I said?"
        ]
      }
    ]
  },
  {
    "name": "Tesla trooper",
    "game": "RA3",
    "groups": [
      {
        "label": "建成",
        "lines": [
          "Trooper, fully charged!"
        ]
      },
      {
        "label": "选中",
        "lines": [
          "Who needs a jump?",
          "Free hook-ups!",
          "Capacitators ready!",
          "Electrodes primed!",
          "Surge protectors on!",
          "I'm wired!",
          "Fully shielded!",
          "Tesla suit ready!"
        ]
      },
      {
        "label": "移动",
        "lines": [
          "Yes, comrade!",
          "Moving out!",
          "Positively!",
          "Full of energy!",
          "In motion!",
          "Advance!",
          "I'll get there!",
          "We're off!",
          "Sparks my interest!",
          "Konechno (Russian: \"of course\")"
        ]
      },
      {
        "label": "特殊技能",
        "lines": [
          "Sorry if I'm a turnoff!",
          "I'm conserving!",
          "Blackout, anyone?",
          "Let's play in the field!",
          "Lights out!",
          "No overcharge protection!",
          "Dampeners active!",
          "Let's make contact!",
          "Is recycled energy!",
          "I'll charge it up!",
          "Give it a boost!",
          "Let's turn it on!"
        ]
      },
      {
        "label": "驻守",
        "lines": [
          "Looks well grounded!",
          "Could use some recharge time.",
          "Is it well insulated?"
        ]
      },
      {
        "label": "攻击",
        "lines": [
          "Let the Joules flow!",
          "Light 'em up!",
          "Hitting switch!",
          "Clear!",
          "AC/DC!",
          "Electrifying!",
          "They could use a little boost!",
          "Give 'em a jolt!",
          "Illuminating!",
          "Completing circuit!",
          "Like a Christmas tree!",
          "Is recycled energy!",
          "Charging up!",
          "Let's light them up!",
          "Time for a shocker!",
          "Insulation won't help!",
          "Let's brighten up their day!",
          "He's fried!",
          "Incoming storm!",
          "Here's your electric bill!",
          "Charge!"
        ]
      },
      {
        "label": "战斗中",
        "lines": [
          "Just go with the flow!",
          "Not a bad conductor!",
          "Electricity is in the air!",
          "Extra crispy!",
          "No resistance!",
          "It will all soon be over!",
          "Amplify!"
        ]
      },
      {
        "label": "受到攻击",
        "lines": [
          "What happened to my shielding?!",
          "Hey, don't be so negative!",
          "They're giving me static!",
          "I may need shock therapy!",
          "Geez, tough crowd!",
          "Was it something I said?"
        ]
      }
    ]
  }
];
