// AUTO-GENERATED by scripts/generate-scenarios.mjs — do not edit by hand.
// Daily-scenario phrasebook (Hong Kong / travel oriented), for the 场景 tab.

export interface ScenarioSentence {
  en: string;
  zh: string;
  tip?: string;
}

export interface Scenario {
  id: string;
  title: string;
  icon: string;
  sentences: ScenarioSentence[];
}

export const SCENARIOS: Scenario[] = [
  {
    "id": "immigration",
    "title": "入境 · 海关",
    "icon": "airplane-outline",
    "sentences": [
      {
        "en": "I'm here for sightseeing.",
        "zh": "我是来旅游的。",
        "tip": "入境官问访港目的时最常用"
      },
      {
        "en": "I'll be staying for five days.",
        "zh": "我会待五天。",
        "tip": "把 five 换成实际天数"
      },
      {
        "en": "I'm staying at a hotel in Tsim Sha Tsui.",
        "zh": "我住在尖沙咀的一家酒店。",
        "tip": "官员问住哪里，说区名最清楚"
      },
      {
        "en": "Here's my passport and return ticket.",
        "zh": "这是我的护照和回程机票。"
      },
      {
        "en": "This is my first time in Hong Kong.",
        "zh": "这是我第一次来香港。"
      },
      {
        "en": "I'm travelling alone. / I'm travelling with my family.",
        "zh": "我一个人来。／我和家人一起来。"
      },
      {
        "en": "Sorry, could you say that again more slowly?",
        "zh": "抱歉，能再慢一点说一遍吗？",
        "tip": "没听懂就用这句，别硬点头"
      },
      {
        "en": "Do I need to fill in an arrival card?",
        "zh": "我需要填入境卡吗？",
        "tip": "香港现在多为电子入境，可先问一句"
      },
      {
        "en": "Could you help me fill in this form? I'm not sure about this part.",
        "zh": "能帮我填一下这张表吗？这部分我不太确定。"
      },
      {
        "en": "I have nothing to declare.",
        "zh": "我没有需要申报的东西。",
        "tip": "走海关绿色通道时说"
      },
      {
        "en": "It's just some snacks and gifts for friends.",
        "zh": "只是一些零食和送朋友的礼物。",
        "tip": "被开箱检查时解释行李内容"
      },
      {
        "en": "Excuse me, where's the baggage claim for flight CX530?",
        "zh": "请问 CX530 航班的行李提取处在哪里？",
        "tip": "换成你的航班号"
      }
    ]
  },
  {
    "id": "transport",
    "title": "交通 · 出行",
    "icon": "train-outline",
    "sentences": [
      {
        "en": "Where can I buy an Octopus card?",
        "zh": "哪里可以买八达通卡？",
        "tip": "到港后先在地铁客服中心或便利店买卡"
      },
      {
        "en": "Can I top up my Octopus here? A hundred dollars, please.",
        "zh": "这里可以给八达通充值吗？充一百块。",
        "tip": "地铁站增值机、7-11、OK便利店都行"
      },
      {
        "en": "Which platform is the train to Tsim Sha Tsui?",
        "zh": "去尖沙咀的车在几号站台？",
        "tip": "站内问工作人员最快"
      },
      {
        "en": "Does this train go to Central, or do I need to change?",
        "zh": "这趟车直接到中环吗，还是要换乘？",
        "tip": "香港换乘站多，先确认再上车"
      },
      {
        "en": "Which exit is closest to the Star Ferry?",
        "zh": "哪个出口离天星小轮最近？",
        "tip": "香港地铁出口多，问对出口省很多路"
      },
      {
        "en": "How much is the Airport Express to Hong Kong Station?",
        "zh": "机场快线到香港站多少钱？",
        "tip": "也可以问 \"Is there a round-trip discount?\"（有往返优惠吗）"
      },
      {
        "en": "Do I need to tap out when I get off?",
        "zh": "下车需要再刷一次卡吗？",
        "tip": "不确定刷卡进出规则时问一句"
      },
      {
        "en": "Excuse me, does this bus stop at Causeway Bay?",
        "zh": "请问这班巴士在铜锣湾停吗？",
        "tip": "上车前问司机，巴士上车即付且不找零"
      },
      {
        "en": "Could you let me know when we're near my stop?",
        "zh": "快到我那站时可以叫我一下吗？",
        "tip": "坐巴士或小巴怕坐过站时用"
      },
      {
        "en": "Could you take me to this address, please?",
        "zh": "麻烦送我去这个地址。",
        "tip": "配合手机上的中文地址给司机看，最保险"
      },
      {
        "en": "Is the meter on?",
        "zh": "打表了吗？",
        "tip": "香港出租车都打表，上车留意一下"
      },
      {
        "en": "You can drop me off right here. Could I get a receipt?",
        "zh": "就在这儿放我下来吧。可以给我张收据吗？",
        "tip": "留收据方便找回落在车上的东西"
      }
    ]
  },
  {
    "id": "chachaanteng",
    "title": "茶餐厅 · 点餐",
    "icon": "cafe-outline",
    "sentences": [
      {
        "en": "Table for one, please.",
        "zh": "一个人，谢谢。",
        "tip": "进门跟店员说人数，茶餐厅常拼台"
      },
      {
        "en": "Is it okay if I share a table?",
        "zh": "拼台可以吗？",
        "tip": "高峰时段店员会让你跟陌生人同桌"
      },
      {
        "en": "Can I see the menu, please?",
        "zh": "可以给我看一下菜单吗？",
        "tip": "菜单常压在玻璃桌面下，也可这样问"
      },
      {
        "en": "I'll have the set B, please.",
        "zh": "我要B餐，谢谢。",
        "tip": "茶餐厅套餐常按A/B/C餐编号"
      },
      {
        "en": "One milk tea, hot — less sugar, please.",
        "zh": "一杯热奶茶，少糖，谢谢。",
        "tip": "少糖说 less sugar，不要糖说 no sugar"
      },
      {
        "en": "Iced lemon tea, and please go easy on the ice.",
        "zh": "冻柠茶，冰少一点。",
        "tip": "少冰也可以说 less ice"
      },
      {
        "en": "One pineapple bun with butter, please.",
        "zh": "一个菠萝油，谢谢。",
        "tip": "夹黄油的菠萝包就是菠萝油"
      },
      {
        "en": "Macaroni soup with ham and egg, please.",
        "zh": "要一份餐蛋通粉，谢谢。",
        "tip": "换面就说 instant noodles 代替 macaroni"
      },
      {
        "en": "Does the set come with a drink?",
        "zh": "套餐包饮料吗？",
        "tip": "很多套餐含饮品，有时加钱换冻饮"
      },
      {
        "en": "How much extra for a cold drink?",
        "zh": "换冻饮要加多少钱？",
        "tip": "冻饮通常加$3-5"
      },
      {
        "en": "Excuse me, could I get the bill?",
        "zh": "不好意思，可以埋单吗？",
        "tip": "也可以直接说 Bill, please."
      },
      {
        "en": "Can I pay by card, or cash only?",
        "zh": "可以刷卡还是只收现金？",
        "tip": "小店常只收现金或八达通"
      }
    ]
  },
  {
    "id": "restaurant",
    "title": "餐厅 · 就餐",
    "icon": "restaurant-outline",
    "sentences": [
      {
        "en": "Hi, I'd like to book a table for two at seven tonight.",
        "zh": "你好，我想订今晚七点两人的位子。",
        "tip": "打电话或在店门口订位"
      },
      {
        "en": "Seven is fully booked? Do you have anything around eight?",
        "zh": "七点满了吗？八点左右有位子吗？",
        "tip": "原定时间没位时改时间"
      },
      {
        "en": "We have a reservation under the name Chan, for two.",
        "zh": "我们有预订，姓陈，两位。",
        "tip": "到店报名字；香港常用英文姓氏拼法"
      },
      {
        "en": "Could we get a table by the window, if possible?",
        "zh": "如果可以的话，能给我们靠窗的位子吗？",
        "tip": "礼貌提要求，加 if possible 不显强硬"
      },
      {
        "en": "Could we have a few more minutes? And what would you recommend?",
        "zh": "能再给我们几分钟吗？你有什么推荐？",
        "tip": "还没决定好又想听建议时"
      },
      {
        "en": "What's your signature dish? Is the set menu better value?",
        "zh": "你们的招牌菜是什么？套餐是不是更划算？",
        "tip": "正式餐厅常有 set menu（套餐）"
      },
      {
        "en": "I'll have the steak, medium rare, please.",
        "zh": "我要牛排，三分熟，谢谢。",
        "tip": "熟度：rare 一分、medium rare 三分、medium 五分、well done 全熟"
      },
      {
        "en": "Does this have any shellfish in it? I'm allergic.",
        "zh": "这个里面有贝类海鲜吗？我过敏。",
        "tip": "点菜前先问，过敏一定要说清楚"
      },
      {
        "en": "Could we order a bit more? Another two of these, please.",
        "zh": "我们想再加点菜，这个再来两份，谢谢。",
        "tip": "加单时指着菜单说最清楚"
      },
      {
        "en": "Sorry, I think this isn't what we ordered.",
        "zh": "抱歉，这好像不是我们点的菜。",
        "tip": "上错菜时用；语气客气容易解决"
      },
      {
        "en": "Could we get the bill, please? Is the service charge included?",
        "zh": "可以结账吗？服务费包含在里面了吗？",
        "tip": "香港正式餐厅通常加一成服务费，加了就不用再给小费"
      },
      {
        "en": "Can I pay by card? And everything was delicious, thank you.",
        "zh": "可以刷卡吗？菜都很好吃，谢谢。",
        "tip": "想分开付就说 Can we split the bill?"
      }
    ]
  },
  {
    "id": "shopping",
    "title": "购物 · 商场",
    "icon": "bag-handle-outline",
    "sentences": [
      {
        "en": "I'm just looking, thanks.",
        "zh": "我先看看，谢谢。",
        "tip": "店员上来问 Can I help you? 时用，礼貌又不尴尬"
      },
      {
        "en": "How much is this? Is it on sale?",
        "zh": "这个多少钱？有在打折吗？",
        "tip": "没看到价钱牌时问；on sale 指正在特价"
      },
      {
        "en": "Can I try this on?",
        "zh": "我可以试穿吗？",
        "tip": "拿着衣服问店员，香港试穿很常见"
      },
      {
        "en": "Where's the fitting room?",
        "zh": "试衣间在哪里？",
        "tip": "店员常回 It's just over there / at the back"
      },
      {
        "en": "Do you have this in a size M?",
        "zh": "这件有 M 码吗？",
        "tip": "换成 small / large / size 8 都可以"
      },
      {
        "en": "It's a bit tight. Do you have one size up?",
        "zh": "有点紧，有大一号的吗？",
        "tip": "太松就说 It's a bit loose, one size down"
      },
      {
        "en": "Do you have this in another colour?",
        "zh": "这个有别的颜色吗？",
        "tip": "香港拼 colour，说 color 一样听得懂"
      },
      {
        "en": "Sorry, we're out of that size.",
        "zh": "抱歉，那个尺码卖完了。",
        "tip": "店员的常见回答，意思是没货了"
      },
      {
        "en": "Any discount if I buy two?",
        "zh": "买两件有优惠吗？",
        "tip": "商场专柜基本不讲价，问多买优惠更自然；街市、旺角小店才可以说 Can you give me a better price?"
      },
      {
        "en": "Can I exchange it if it doesn't fit?",
        "zh": "如果不合身可以换吗？",
        "tip": "记得同时说 Can I have the receipt? 换货一般要收据"
      },
      {
        "en": "Can I pay by WeChat Pay or Alipay?",
        "zh": "可以用微信或支付宝付款吗？",
        "tip": "也可问 Do you take Octopus / UnionPay?（八达通、银联）"
      },
      {
        "en": "OK, I'll take it.",
        "zh": "好，我买这个。",
        "tip": "决定买了就这么说，店员会带你去收银台"
      }
    ]
  },
  {
    "id": "hotel",
    "title": "酒店 · 入住",
    "icon": "bed-outline",
    "sentences": [
      {
        "en": "Hi, I have a reservation under the name Zhang.",
        "zh": "你好，我有预订，姓张。",
        "tip": "到前台第一句话，报姓氏就行"
      },
      {
        "en": "Here's my passport and the booking confirmation.",
        "zh": "这是我的护照和订单确认单。",
        "tip": "香港酒店入住一般要看护照"
      },
      {
        "en": "Is early check-in possible? My flight landed this morning.",
        "zh": "可以提前入住吗？我的航班今早到的。",
        "tip": "标准入住时间通常是下午三点"
      },
      {
        "en": "Do you need a deposit? Can I pay by card?",
        "zh": "需要押金吗？可以用信用卡吗？",
        "tip": "香港酒店常预授权押金，退房后退回"
      },
      {
        "en": "Could I get a room on a higher floor, away from the elevator?",
        "zh": "能给我一间高层、离电梯远一点的房间吗？",
        "tip": "想安静一点就这么说"
      },
      {
        "en": "Is breakfast included? What time does it start?",
        "zh": "含早餐吗？几点开始？"
      },
      {
        "en": "What's the Wi-Fi name and password?",
        "zh": "Wi-Fi 名字和密码是什么？"
      },
      {
        "en": "Could I have two more towels and an extra blanket, please?",
        "zh": "能再给我两条毛巾和一条被子吗？",
        "tip": "打电话到前台也可以这样说"
      },
      {
        "en": "The air conditioning isn't working — could someone come and take a look?",
        "zh": "空调坏了，能派人来看一下吗？",
        "tip": "换成 the shower / the TV / the lock 也通用"
      },
      {
        "en": "The room next door is really noisy. Could I change rooms?",
        "zh": "隔壁房间太吵了，可以换房吗？"
      },
      {
        "en": "Can I leave my luggage here after check-out? I'll pick it up around five.",
        "zh": "退房后行李可以寄存在这里吗？我大概五点来拿。",
        "tip": "香港酒店基本都免费寄存"
      },
      {
        "en": "I'd like to check out. Could I have the receipt, please?",
        "zh": "我要退房，能给我一张收据吗？",
        "tip": "报销记得说 invoice"
      }
    ]
  },
  {
    "id": "directions",
    "title": "问路 · 导航",
    "icon": "navigate-outline",
    "sentences": [
      {
        "en": "Excuse me, how do I get to the Star Ferry Pier?",
        "zh": "打扰一下，请问天星小轮码头怎么走？",
        "tip": "最通用的问路开场，先说 Excuse me 再问"
      },
      {
        "en": "Sorry, I'm a bit lost. Is this the right way to Tsim Sha Tsui?",
        "zh": "不好意思，我有点迷路了。去尖沙咀是这个方向吗？",
        "tip": "走了一段不确定方向时用"
      },
      {
        "en": "Which exit should I take for the Peak Tram?",
        "zh": "去山顶缆车要走哪个出口？",
        "tip": "港铁出口很多，问 Exit A/B 最省事"
      },
      {
        "en": "Is it within walking distance, or should I take the MTR?",
        "zh": "走过去近吗，还是坐地铁比较好？",
        "tip": "判断要不要坐车"
      },
      {
        "en": "How long does it take to walk there?",
        "zh": "走过去要多久？"
      },
      {
        "en": "Which line should I take to Central?",
        "zh": "去中环要坐哪条线？",
        "tip": "香港地铁按线路名走，比如 Tsuen Wan Line"
      },
      {
        "en": "Do I need to change trains? Where do I transfer?",
        "zh": "需要换车吗？在哪里换？",
        "tip": "换乘就说 transfer 或 change trains"
      },
      {
        "en": "Does this bus go to Mong Kok?",
        "zh": "这班车去旺角吗？",
        "tip": "上车前问司机最快"
      },
      {
        "en": "Can I use my Octopus card on this?",
        "zh": "这个可以用八达通吗？",
        "tip": "小巴、电车、渡轮都能问一句"
      },
      {
        "en": "Could you show me on the map?",
        "zh": "可以在地图上指给我看吗？",
        "tip": "听不懂方向时，直接把手机地图递过去"
      },
      {
        "en": "Sorry, could you say that again more slowly?",
        "zh": "不好意思，可以再慢一点说一遍吗？",
        "tip": "没听清就用这句，比 pardon 更自然"
      },
      {
        "en": "Got it, thanks a lot for your help!",
        "zh": "明白了，非常感谢你的帮助！",
        "tip": "结束对话，礼貌收尾"
      }
    ]
  },
  {
    "id": "convenience",
    "title": "便利店 · 超市",
    "icon": "cart-outline",
    "sentences": [
      {
        "en": "Do you take Octopus?",
        "zh": "你们收八达通吗？",
        "tip": "香港便利店基本都收，问一句最快"
      },
      {
        "en": "I'd like to add money to my Octopus card, please. Two hundred.",
        "zh": "我想给八达通充值，两百块。",
        "tip": "7-Eleven、OK便利店柜台都能充"
      },
      {
        "en": "Can I have a receipt?",
        "zh": "可以给我张收据吗？",
        "tip": "报销或核对金额时用"
      },
      {
        "en": "Do you have a plastic bag? How much is it?",
        "zh": "有塑料袋吗？多少钱？",
        "tip": "香港胶袋要收费，通常一毛到一块"
      },
      {
        "en": "No bag, thanks. I've got my own.",
        "zh": "不用袋子，谢谢，我自己带了。"
      },
      {
        "en": "Excuse me, where can I find bottled water?",
        "zh": "请问瓶装水在哪里？",
        "tip": "超市里找货架时用，换成任何商品名都行"
      },
      {
        "en": "Is this on sale? / Is this the discounted price?",
        "zh": "这个在打折吗？／这是折后价吗？",
        "tip": "看到「特价」标签但不确定时"
      },
      {
        "en": "Could you heat this up for me, please?",
        "zh": "可以帮我加热一下吗？",
        "tip": "买便当、包子时说"
      },
      {
        "en": "Can I get a straw and a napkin?",
        "zh": "可以给我一根吸管和一张纸巾吗？"
      },
      {
        "en": "Sorry, I don't need this one. Please take it off.",
        "zh": "不好意思，这个我不要了，麻烦取消掉。",
        "tip": "结账时临时改主意"
      },
      {
        "en": "Where's the toilet? Do I need a key?",
        "zh": "洗手间在哪里？需要钥匙吗？",
        "tip": "香港说 toilet 比 restroom 更常见，有些店厕所要拿钥匙"
      },
      {
        "en": "Can I pay by phone? I'll use Alipay / WeChat Pay.",
        "zh": "可以手机支付吗？我用支付宝／微信。",
        "tip": "香港很多店支持，但小店可能只收现金或八达通"
      }
    ]
  },
  {
    "id": "medical",
    "title": "看病 · 药店",
    "icon": "medkit-outline",
    "sentences": [
      {
        "en": "Excuse me, do you have anything for a cold?",
        "zh": "你好，有没有治感冒的药？",
        "tip": "进药店最万能的开场，屈臣氏/万宁都能用"
      },
      {
        "en": "I have a sore throat and a runny nose.",
        "zh": "我喉咙痛，还流鼻水。",
        "tip": "描述症状最常用的组合；咳嗽是 a cough"
      },
      {
        "en": "I've had a fever since last night — around 38.5 degrees.",
        "zh": "我从昨晚开始发烧，大概38.5度。",
        "tip": "香港用摄氏度，直接说数字就行"
      },
      {
        "en": "My stomach hurts and I have diarrhea.",
        "zh": "我肚子痛，还拉肚子。",
        "tip": "想说吃坏东西：I think it's something I ate"
      },
      {
        "en": "Do you have any painkillers?",
        "zh": "有止痛药吗？",
        "tip": "香港最常见的是 Panadol，直接说品牌店员更快懂"
      },
      {
        "en": "Can I speak to the pharmacist?",
        "zh": "可以找药剂师聊一下吗？",
        "tip": "招牌有绿色十字的是大药房，有注册药剂师可咨询"
      },
      {
        "en": "Does this need a prescription?",
        "zh": "这个需要处方吗？",
        "tip": "抗生素、部分感冒药在香港要处方"
      },
      {
        "en": "How do I take this? Before or after meals?",
        "zh": "这个怎么吃？饭前还是饭后？",
        "tip": "追问次数：How many times a day?"
      },
      {
        "en": "I'm allergic to penicillin.",
        "zh": "我对青霉素过敏。",
        "tip": "有过敏史一定要主动讲，换药名即可"
      },
      {
        "en": "Where's the nearest clinic that's open now?",
        "zh": "最近的、现在还开门的诊所在哪里？",
        "tip": "晚上找 24-hour clinic，商场楼上私家诊所很常见"
      },
      {
        "en": "Can I walk in without an appointment? How much is the consultation?",
        "zh": "不预约可以直接看吗？看诊费多少？",
        "tip": "看完说 Can I have a receipt? 方便回去保险理赔"
      },
      {
        "en": "This is an emergency — please call an ambulance.",
        "zh": "这是紧急情况，请叫救护车。",
        "tip": "香港急救电话999；急诊叫 A&E，不叫 ER"
      }
    ]
  },
  {
    "id": "money",
    "title": "兑换 · 支付",
    "icon": "cash-outline",
    "sentences": [
      {
        "en": "Where's the nearest money changer?",
        "zh": "最近的兑换店在哪里？",
        "tip": "香港街边找钱庄，比机场汇率好"
      },
      {
        "en": "What's today's rate for RMB to Hong Kong dollars?",
        "zh": "今天人民币换港币的汇率是多少？"
      },
      {
        "en": "Is there a commission or any handling fee?",
        "zh": "要收佣金或手续费吗？",
        "tip": "换钱前一定先问，有些店汇率好但收费高"
      },
      {
        "en": "Could you give me some small bills — fifties and twenties?",
        "zh": "能给我一些小面额的吗，五十和二十的。",
        "tip": "坐小巴、买小吃很需要零钱"
      },
      {
        "en": "Is there an ATM around here? Does it take UnionPay?",
        "zh": "这附近有ATM吗？能用银联卡吗？"
      },
      {
        "en": "My card is stuck in the machine. Who should I call?",
        "zh": "我的卡卡在机器里了，该打电话给谁？",
        "tip": "急事时用，机器旁一般有客服电话"
      },
      {
        "en": "Do you take WeChat Pay or Alipay?",
        "zh": "你们收微信支付或支付宝吗？",
        "tip": "香港很多店支持，但小店可能只收现金"
      },
      {
        "en": "Sorry, cash only. / I'll just pay by card then.",
        "zh": "抱歉，只收现金。／那我刷卡吧。",
        "tip": "前半句是店家会说的，后半句你回"
      },
      {
        "en": "Should I scan your code, or do you scan mine?",
        "zh": "我扫你还是你扫我？",
        "tip": "手机付款时最常用的一句"
      },
      {
        "en": "Sorry, I think the change is ten dollars short.",
        "zh": "不好意思，找的钱好像少了十块。",
        "tip": "语气客气，说 I think 比较不冲"
      },
      {
        "en": "Can I get a receipt? I need it for reimbursement.",
        "zh": "能给我张收据吗？我要报销。",
        "tip": "要正式发票可以说 an official invoice"
      },
      {
        "en": "Can I top up my Octopus card here? A hundred, please.",
        "zh": "这里能给八达通充值吗？充一百。",
        "tip": "便利店、地铁站都可以充"
      }
    ]
  },
  {
    "id": "social",
    "title": "日常 · 寒暄",
    "icon": "chatbubbles-outline",
    "sentences": [
      {
        "en": "Hi, how's it going?",
        "zh": "嗨，最近怎么样？",
        "tip": "最自然的打招呼，比 How are you 更口语"
      },
      {
        "en": "Good morning! Lovely weather today.",
        "zh": "早上好！今天天气真好。",
        "tip": "和酒店前台、店员开场闲聊"
      },
      {
        "en": "Sorry, could you help me with something?",
        "zh": "不好意思，能帮我个忙吗？",
        "tip": "请求帮助前的开场，礼貌又直接"
      },
      {
        "en": "Excuse me, do you speak Mandarin?",
        "zh": "打扰一下，你会说普通话吗？",
        "tip": "香港很多人会普通话，先问一句能省事"
      },
      {
        "en": "Thanks so much, I really appreciate it.",
        "zh": "太感谢你了，真的很感激。",
        "tip": "别人认真帮了你之后说"
      },
      {
        "en": "No worries, thanks anyway.",
        "zh": "没关系，还是谢谢你。",
        "tip": "对方帮不上忙时，体面收尾"
      },
      {
        "en": "Sorry, my English isn't great. Could you speak a bit slower?",
        "zh": "抱歉，我英文不太好，能说慢一点吗？",
        "tip": "听不懂时最有用的一句"
      },
      {
        "en": "Sorry, excuse me.",
        "zh": "抱歉，让一下。",
        "tip": "地铁、电梯里挤过去或碰到人时"
      },
      {
        "en": "Is this your first time here too?",
        "zh": "你也是第一次来吗？",
        "tip": "排队、等车时开启闲聊"
      },
      {
        "en": "I'm just visiting for a few days.",
        "zh": "我就来玩几天。",
        "tip": "回答“你是本地人吗/来多久”"
      },
      {
        "en": "Nice chatting with you. Take care!",
        "zh": "和你聊得很开心，保重！",
        "tip": "闲聊结束时自然告别"
      },
      {
        "en": "See you around. Have a good one!",
        "zh": "再见啦，祝你愉快！",
        "tip": "轻松的道别，对店员、司机都能用"
      }
    ]
  },
  {
    "id": "emergency",
    "title": "紧急 · 求助",
    "icon": "alert-circle-outline",
    "sentences": [
      {
        "en": "Can you help me? It's an emergency.",
        "zh": "能帮我一下吗？情况紧急。",
        "tip": "拦住路人或店员时的第一句，先说明紧急"
      },
      {
        "en": "Please call 999.",
        "zh": "请打999。",
        "tip": "香港报警、叫救护车、火警都是999"
      },
      {
        "en": "We need an ambulance. Someone is hurt.",
        "zh": "我们需要救护车，有人受伤了。"
      },
      {
        "en": "I don't feel well. I feel dizzy and I can't breathe properly.",
        "zh": "我不太舒服，头晕，呼吸有点困难。",
        "tip": "描述症状越具体越好，方便对方判断"
      },
      {
        "en": "Where's the nearest hospital or clinic?",
        "zh": "最近的医院或诊所在哪里？"
      },
      {
        "en": "I've lost my child. He's six years old, wearing a red T-shirt.",
        "zh": "我孩子走失了，他六岁，穿红色T恤。",
        "tip": "立刻说年龄和衣服颜色，商场和港铁站会广播帮找"
      },
      {
        "en": "Can you make an announcement? My friend and I got separated.",
        "zh": "能帮忙广播一下吗？我和朋友走散了。",
        "tip": "在商场服务台或港铁站客务中心用"
      },
      {
        "en": "My phone was stolen. I want to report it to the police.",
        "zh": "我的手机被偷了，我要报警。"
      },
      {
        "en": "I left my bag on the MTR. Where's the lost property office?",
        "zh": "我把包忘在港铁上了，失物认领处在哪里？",
        "tip": "港铁失物处在九龙湾站，也可先问站内职员"
      },
      {
        "en": "I lost my passport. I need to contact my consulate.",
        "zh": "我的护照丢了，我需要联系领事馆。",
        "tip": "护照丢失要先报警拿报案纸，再去领事馆"
      },
      {
        "en": "Sorry, could you speak a bit slower? My English isn't very good.",
        "zh": "抱歉，能说慢一点吗？我英文不太好。"
      },
      {
        "en": "Does anyone here speak Mandarin?",
        "zh": "这里有人会说普通话吗？",
        "tip": "香港很多人会普通话，紧急时直接问最快"
      }
    ]
  }
];
